# Generated by Django 5.2.1 on 2025-11-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user_extras', '0002_alter_favorite_unique_together_favorite_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('user', 'course')},
        ),
    ]
