# Generated by Django 5.2.1 on 2025-11-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_extras', '0003_chatmessage_course_alter_chatmessage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together=set(),
        ),
    ]
