# Generated by Django 5.2.1 on 2025-10-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user_progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='QuizChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapter')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='user_progress.quizcourseprogress')),
            ],
            options={
                'unique_together': {('course_progress', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='QuizSubtopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('chapter_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='user_progress.quizchapterprogress')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subtopic')),
            ],
            options={
                'unique_together': {('chapter_progress', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('subtopic_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_progress.quizsubtopicprogress')),
            ],
            options={
                'unique_together': {('subtopic_progress', 'question')},
            },
        ),
    ]
