# Generated by Django 5.2.1 on 2025-10-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user_progress', '0004_quizcourseprogress_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcourseprogress',
            name='last_viewed_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.question'),
        ),
        migrations.AddField(
            model_name='testcourseprogress',
            name='last_viewed_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.question'),
        ),
    ]
