# Generated by Django 5.2.1 on 2025-10-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0005_quizcourseprogress_last_viewed_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcourseprogress',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizcourseprogress',
            name='flagged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizcourseprogress',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcourseprogress',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcourseprogress',
            name='flagged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcourseprogress',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
